-- Basic
require("core.plugins")
require("core.colors")
require("core.mappings")
require("core.configs")
require("core.diagnostics")

-- Plugins
require("plugins.neotree")
require("plugins.treesitter")
require("plugins.lsp")
-- require("plugins.mason")
require("plugins.cmp")
require("plugins.telescope")
-- require("plugins.nonels")
require("plugins.formatters")
require("plugins.lint")
require("plugins.hop")
require("plugins.toggleterm")
require("plugins.buffline")
require("plugins.dashboard")
require("plugins.gitsigns")
require("plugins.lualine")
-- require("plugins.whichkey")
require("plugins.autopairs")
require("plugins.comments")
require("plugins.dap_go")
require("plugins.dap_python")
require("plugins.dap_c")
require("plugins.dap_bash")
require("plugins.dap_ui")
require("plugins.ctags")
require("plugins.switch_window")
require("plugins.vimvsnip")
require("plugins.undo_tree")
require("plugins.refactoring")
require("plugins.folding")
require("plugins.langmapper")
require("plugins.commands")
require("plugins.quickfixformat")
require("plugins.nvim_events")
require("plugins.switchbuffer")
require("plugins.surround")
require("plugins.marks")
require("plugins.img_clip")
require("plugins.spectre")
require("plugins.csvview")
